"""Initial migration.

Revision ID: eca50f341e44
Revises: 
Create Date: 2021-07-18 21:56:08.954992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca50f341e44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('musician_composition_id_fkey', 'musician', type_='foreignkey')
    op.drop_column('musician', 'composition_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musician', sa.Column('composition_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('musician_composition_id_fkey', 'musician', 'composition', ['composition_id'], ['id'])
    # ### end Alembic commands ###
